\input texinfo
@setfilename tgicmp.info
@documentencoding UTF-8
@include PACKAGE.texi
@settitle @code{tgicmp}

@include CC0-1.0.copying.texi

@titlepage
@title @code{tgicmp}
@subtitle Type-generic integer comparisons in C
@subtitle @code{v@value{VERSION}} (@value{DATE})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top @code{tgicmp}

This manual is for @code{tgicmp v@value{VERSION}} (@value{DATE}), a
library for performing type-generic integer comparisons in C.

@end ifnottex

@menu
* Copyright information::
* Introduction::
* The CC0 1.0 Universal Public Domain Dedication: The CC0 1-0 Universal Public Domain Dedication.
@end menu

@node Copyright information
@unnumbered Copyright information

The authors of @code{tgicmp} have waived all copyright and
related or neighboring rights to the extent permitted by
law as described by the CC0 1.0 Universal Public Domain
Dedication. @xref{The CC0 1-0 Universal Public Domain Dedication},
for the full dedication. It may also be available at
@url{https://creativecommons.org/publicdomain/zero/1.0/}.

@node Introduction
@chapter Introduction

@include CC0-1.0.appendix.texi

@bye

@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
